# Generated by Django 2.0.1 on 2018-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('dateDeNaissance', models.DateTimeField(verbose_name='dateDeNaissance')),
                ('localisation', models.CharField(max_length=2001)),
                ('competencePossede', models.CharField(max_length=200)),
                ('formationPossede', models.CharField(max_length=200)),
                ('diplomePossede', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
