# Generated by Django 2.0.1 on 2018-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='motDePasse',
            field=models.CharField(default='login', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pseudo',
            field=models.CharField(default='login', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='localisation',
            field=models.CharField(max_length=200),
        ),
    ]
