# Generated by Django 2.0.1 on 2018-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_auto_20180205_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='dateDeNaissance',
            field=models.CharField(max_length=200),
        ),
    ]
