# Generated by Django 2.0.1 on 2018-02-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_auto_20180207_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='motDePasse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='pseudo',
        ),
    ]
