# Generated by Django 2.0.1 on 2018-02-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_auto_20180207_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='competencePossede',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateDeNaissance',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='description',
            field=models.CharField(default='null', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='diplomePossede',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='formationPossede',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='localisation',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
    ]
