# Generated by Django 2.0.1 on 2018-02-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_auto_20180207_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
