# Generated by Django 2.0.1 on 2018-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_utilisateur_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='experiencePossede',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='qualite',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
