# Generated by Django 2.0.1 on 2018-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_auto_20180208_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='competencePossede',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='diplomePossede',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='experiencePossede',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='formationPossede',
        ),
    ]
