# Generated by Django 2.0.1 on 2018-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0003_auto_20180214_1100'),
        ('utilisateur', '0014_auto_20180213_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.niveauEtude'),
        ),
    ]
