# Generated by Django 2.0.1 on 2018-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0016_auto_20180214_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
    ]
