# Generated by Django 2.0.1 on 2018-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0006_qualite'),
        ('utilisateur', '0017_auto_20180214_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='experience',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='qualite',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='qualite',
            field=models.ManyToManyField(to='composantProfil.Qualite'),
        ),
    ]
