# Generated by Django 2.0.1 on 2018-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0018_auto_20180214_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='experience',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
    ]
