# Generated by Django 2.0.1 on 2018-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0008_auto_20180214_1625'),
        ('utilisateur', '0021_auto_20180214_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='competence',
            field=models.ManyToManyField(to='composantProfil.Competence'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='experience',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
    ]
