# Generated by Django 2.0.1 on 2018-02-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0022_auto_20180215_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='competence',
            field=models.ManyToManyField(to='composantProfil.Competence'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='experience',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
    ]
