# Generated by Django 2.0.1 on 2018-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0024_auto_20180220_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='competence',
            field=models.ManyToManyField(to='composantProfil.Competence'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='experience',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveauEtude',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
    ]
