# Generated by Django 2.0.2 on 2018-02-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composantProfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, max_length=200)),
                ('typeContrat', models.CharField(blank=True, max_length=200)),
                ('dateDebut', models.CharField(blank=True, max_length=200)),
                ('dateFin', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('typeContrat', models.CharField(blank=True, max_length=200, null=True)),
                ('localisation', models.CharField(blank=True, max_length=200, null=True)),
                ('competenceRequise', models.CharField(blank=True, max_length=200, null=True)),
                ('dateDebut', models.CharField(blank=True, max_length=200, null=True)),
                ('dureeContrat', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('diplomeRequis', models.ManyToManyField(blank=True, to='composantProfil.NiveauEtude')),
                ('experienceRequise', models.ManyToManyField(blank=True, to='composantProfil.Experience')),
                ('metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='composantProfil.Metier')),
            ],
        ),
    ]
