# Generated by Django 2.0.1 on 2018-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metier', models.CharField(max_length=200)),
                ('typeContrat', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=2001)),
                ('competencePossede', models.CharField(max_length=200)),
                ('diplomePossede', models.CharField(max_length=200)),
                ('dateDebut', models.DateTimeField(verbose_name='dateDebut')),
                ('dureeDisponibilite', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metier', models.CharField(max_length=200)),
                ('typeContrat', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('competenceRequise', models.CharField(max_length=200)),
                ('diplomeRequis', models.CharField(max_length=200)),
                ('dateDebut', models.DateTimeField(verbose_name='dateDebut')),
                ('dureeContrat', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
