# Generated by Django 2.0.2 on 2018-02-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composantProfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeContrat', models.CharField(blank=True, max_length=200)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('typeContrat', models.CharField(blank=True, max_length=200)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='composantProfil.Metier')),
                ('competencePossede', models.ManyToManyField(blank=True, to='composantProfil.Competence')),
                ('experiencePossede', models.ManyToManyField(blank=True, to='composantProfil.Experience')),
                ('qualitePossede', models.ManyToManyField(blank=True, to='composantProfil.Qualite')),
            ],
        ),
    ]
