# Generated by Django 2.0.1 on 2018-02-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('composantProfil', '0001_initial'),
        ('offre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='competencePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.Competence'),
        ),
        migrations.AddField(
            model_name='demande',
            name='demandeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='diplomePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.NiveauEtude'),
        ),
        migrations.AddField(
            model_name='demande',
            name='experiencePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.Experience'),
        ),
        migrations.AddField(
            model_name='demande',
            name='formations',
            field=models.ManyToManyField(blank=True, to='composantProfil.Formation'),
        ),
        migrations.AddField(
            model_name='demande',
            name='qualitePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.Qualite'),
        ),
    ]
