# Generated by Django 2.0.1 on 2018-02-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='metier',
            new_name='metieR',
        ),
    ]
