# Generated by Django 2.0.1 on 2018-02-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0002_auto_20180201_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='metieR',
            new_name='metier',
        ),
    ]
