# Generated by Django 2.0.1 on 2018-02-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('offre', '0003_auto_20180205_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='demandeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur'),
        ),
        migrations.AddField(
            model_name='offre',
            name='recruteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur'),
        ),
    ]
