# Generated by Django 2.0.1 on 2018-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0005_auto_20180205_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='titre',
            field=models.CharField(default='h', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='titre',
            field=models.CharField(default='h', max_length=200),
            preserve_default=False,
        ),
    ]
