# Generated by Django 2.0.1 on 2018-02-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0006_auto_20180206_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='titre',
        ),
    ]
