# Generated by Django 2.0.1 on 2018-02-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0007_remove_demande_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='demandeur',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='recruteur',
        ),
    ]
