# Generated by Django 2.0.1 on 2018-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0009_auto_20180207_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='experienceRequise',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
