# Generated by Django 2.0.1 on 2018-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0006_qualite'),
        ('offre', '0011_auto_20180214_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='experiencePossede',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AddField(
            model_name='demande',
            name='qualitePossede',
            field=models.ManyToManyField(to='composantProfil.Qualite'),
        ),
        migrations.RemoveField(
            model_name='demande',
            name='diplomePossede',
        ),
        migrations.AddField(
            model_name='demande',
            name='diplomePossede',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
        migrations.RemoveField(
            model_name='offre',
            name='diplomeRequis',
        ),
        migrations.AddField(
            model_name='offre',
            name='diplomeRequis',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
        migrations.RemoveField(
            model_name='offre',
            name='experienceRequise',
        ),
        migrations.AddField(
            model_name='offre',
            name='experienceRequise',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
    ]
