# Generated by Django 2.0.1 on 2018-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0014_auto_20180214_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='diplomePossede',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='experiencePossede',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='diplomeRequis',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='experienceRequise',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
    ]
