# Generated by Django 2.0.1 on 2018-02-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0016_auto_20180215_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='diplomePossede',
            field=models.ManyToManyField(to='composantProfil.NiveauEtude'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='experiencePossede',
            field=models.ManyToManyField(to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='competenceRequise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='dateDebut',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='diplomeRequis',
            field=models.ManyToManyField(blank=True, to='composantProfil.NiveauEtude'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='dureeContrat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='experienceRequise',
            field=models.ManyToManyField(blank=True, to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='localisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='composantProfil.Metier'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='typeContrat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
