# Generated by Django 2.0.1 on 2018-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0009_formation'),
        ('offre', '0018_auto_20180220_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='dureeDisponibilite',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='metier',
        ),
        migrations.AddField(
            model_name='demande',
            name='categorie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='dateFin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='formations',
            field=models.ManyToManyField(blank=True, to='composantProfil.Formation'),
        ),
        migrations.RemoveField(
            model_name='demande',
            name='competencePossede',
        ),
        migrations.AddField(
            model_name='demande',
            name='competencePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.Competence'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='dateDebut',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='demande',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='demande',
            name='diplomePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.NiveauEtude'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='experiencePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.Experience'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='qualitePossede',
            field=models.ManyToManyField(blank=True, to='composantProfil.Qualite'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='typeContrat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='offre',
            name='diplomeRequis',
            field=models.ManyToManyField(blank=True, to='composantProfil.NiveauEtude'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='experienceRequise',
            field=models.ManyToManyField(blank=True, to='composantProfil.Experience'),
        ),
    ]
