# Generated by Django 2.0.1 on 2018-02-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composantProfil.cartePresentation')),
            ],
        ),
        migrations.CreateModel(
            name='diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composantProfil.cartePresentation')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composantProfil.cartePresentation')),
            ],
        ),
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composantProfil.cartePresentation')),
            ],
        ),
    ]
