# Generated by Django 2.0.1 on 2018-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='carte',
        ),
        migrations.RemoveField(
            model_name='diplome',
            name='carte',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='carte',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='carte',
        ),
        migrations.DeleteModel(
            name='cartePresentation',
        ),
    ]
