# Generated by Django 2.0.1 on 2018-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0003_auto_20180214_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formation',
        ),
        migrations.RenameField(
            model_name='niveauetude',
            old_name='contenu',
            new_name='domaine',
        ),
        migrations.AddField(
            model_name='niveauetude',
            name='duree',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
