# Generated by Django 2.0.1 on 2018-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0004_auto_20180214_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
