# Generated by Django 2.0.1 on 2018-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0005_metier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=200)),
            ],
        ),
    ]
