# Generated by Django 2.0.1 on 2018-02-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0006_qualite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='contenu',
        ),
        migrations.AddField(
            model_name='experience',
            name='metierPratique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='composantProfil.Qualite'),
        ),
    ]
