# Generated by Django 2.0.1 on 2018-02-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0007_auto_20180214_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='intitule',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='metierPratique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='composantProfil.Metier'),
        ),
    ]
