# Generated by Django 2.0.1 on 2018-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composantProfil', '0008_auto_20180214_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
            ],
        ),
    ]
